#!/bin/bash
#SBATCH --job-name a_0001
#SBATCH --partition docker
#SBATCH --time UNLIMITED
#SBATCH --mincpus 6
#SBATCH --mem-per-cpu 2g
#SBATCH --output /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/_output.txt
#SBATCH --error /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/_error.txt


# run Bowtie2
docker run --rm=true \
  -v /datastore:/datastore:shared \
  -v /home/dbortone:/home/dbortone \
  dockerreg.bioinf.unc.edu:5000/bowtie2_2.3.3.1:1 bash -c \
  'bowtie2 \
    --threads 6 \
    -x /datastore/nextgenout2/share/labs/imgf/ref/bowtie2-build/bowtie2-hg38 \
    -1 /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/stig_rnaseq/output/a_0001/a_0001_R1.degraded.fastq.gz \
    -2 /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/stig_rnaseq/output/a_0001/a_0001_R2.degraded.fastq.gz \
    -S /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/a_0001.sam'


# convert samfile to sorted bam and index it
samtools view -@ 6 -S -b /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/a_0001.sam > /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/unsorted_a_0001.bam
samtools sort -@ 6 -o /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/a_0001.bam /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/unsorted_a_0001.bam
samtools index -@ 6 /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/a_0001.bam


# run TRUST
docker run --rm=true \
  -v /datastore:/datastore:shared \
  -v /home/dbortone:/home/dbortone \
  dockerreg.bioinf.unc.edu:5000/trust_3.0.1:1 bash -c \
  'trust \
    -H \
    -E \
    --CoreN=6 \
    --genome=hg38 \
    -f /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/a_0001.bam \
    -o /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001/'


# clean up files
find /home/dbortone/scratch/Optimize_Diversity_Metrics_CRSV1371/trust_rnaseq/output/a_0001 -type f \
  -not -name '*-TCR-ALL-extended.txt' \
  -not -name '*-TCR-ALL.txt' \
  -not -name '*_error.txt' \
  -not -name '*_output.txt' \
  -delete

